### PR TITLE
Configure distutils

### PR DESCRIPTION
**Pull request by decentral1se**
This PR introduces `distutils` support which gives us: 
- `pip` enabled installed via a `pip install -e .`
- `pytest` integration with `python setup.py test` (and `tox` can fit in nicely after!)
- `pypi` upload/register functionality (should be ready to rip? Haven't tested it)
- CLI entry points out of the box via `distutils`

If you have a [pypitest](http://testpypi.python.org/pypi?%3Aaction=register_form) account, you should be able to successfully run the upload to `pypitest` to see if things work. 

```
$ python setup.py register -r pypitest
$ python setup.py sdist upload -r pypitest
```

I haven't introduced any functional changes to the code, just arranged the boilerplate. I have moved the `if __name__ == "__main__":` from `vbbvg.py` into a `__main__.py` to act as the CLI entry point.

Let me know what you think  :+1: 

EDIT: excuse the ridiculous line count for the changes, that is because of the `pytest` boilerplate file which is in `test/runtests.py`!

### CODE REVIEW

**Comment by deeplook** [comment]
Thanks! Looks great! I just don't have the time to check. If you say it does what it should, I'll just merge your PR. Feel free to add a contributors file listing you, too, (now or later)! ;-)

**Comment by decentral1se** [comment]
Oh yeah, a contributors list, nice idea. Well, have a look when you have a chance, no rush.

**Comment by deeplook** [comment]
So be it! Will check later... Thanks, again! ;-)

**Comment by deeplook** [comment]
Almost. You don't seem to install the file vbbvg_stops.csv, do you? So you get e.g. this when calling `vbbvg --stop Möckernbrücke`:

```
[...]
IOError: File /opt/lib/python2.7/site-packages/vbbvg-0.0.1-py2.7.egg/vbbvg/vbbvg_stops.csv does not exist
```

**Comment by decentral1se** [comment]
oof, nice catch ... revenge of the typo, see referenced PR :bomb:

**Pull request merged**
